// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package oapi

// Example defines model for Example.
type Example struct {
	NullableOptional nullable.Nullable[string] `json:"NullableOptional,omitempty"`
	NullableRequired nullable.Nullable[string] `json:"NullableRequired"`
	Optional         *string                   `json:"Optional,omitempty"`
	Required         string                    `json:"Required"`
}
