// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ExampleGet implements GET /example operation.
//
// GET /example
func (UnimplementedHandler) ExampleGet(ctx context.Context) (r *Example, _ error) {
	return r, ht.ErrNotImplemented
}
